inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rake.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude
    -
require: rubocop-performance

AllCops:
  TargetRubyVersion: 3.4.1
