name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    name: Check for vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  lint:
    name: Lint codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Enable Corepack & Set Correct Yarn Version
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Ruby code for consistent style
        run: bin/rubocop -f github

      - name: Lint JavaScript code for consistent style
        run: yarn lint

      - name: Check that there is no unlocalised text in templates
        run: bundler exec l10nizer

      - name: Check that translations are normalised
        run: bundler exec i18n-tasks check-normalized

      - name: Check that no translations are missing
        run: bundler exec i18n-tasks missing

      - name: Check that there are no unused translations
        run: bundler exec i18n-tasks unused

  spelling:
    name: Check spelling and typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4
    - name: Spell Check Repo
      uses: crate-ci/typos@v1.33.1

  specs:
    name: Run specs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Enable Corepack & Set Correct Yarn Version
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build CSS
        run: yarn build:css

      - name: Precompile assets
        run: bin/rails assets:precompile

      - name: Run specs
        run: bundle exec rspec
